version: "3.8"

services:
  ftcawards:
    networks:
      - interlink_network
    image: registry.digitalocean.com/schoollabsio/ftc-award-script:${COMMIT_SHA}
    command: npm run start

networks:
  interlink_network:
    name: interlink
    external: true
